In [1]:
import os
from pathlib import Path
import pandas as pd
import numpy as np

In [2]:
# Obtener la raíz del proyecto (sube dos niveles desde notebooks/)
PROJECT_ROOT = Path().resolve().parents[1]
# Construir la ruta al archivo
data_path = PROJECT_ROOT / "data" / "raw" / "Municipios.xlsx"
print(f"Ruta del archivo: {data_path}")

Ruta del archivo: /home/ddayann/proyectos/Coffe/proyecto_aplicado_en_analitica_de_datos/data/raw/Municipios.xlsx

In [3]:
Municipios = pd.read_excel(data_path, sheet_name="Municipios")
Municipios.head()

,OBJECTID,MpCodigo,MpNombre,MpArea,MpNorma,MpCategor,MpAltitud,Restriccion,Depto,SHAPE_Length,SHAPE_Area,Area_CTM
0,8,91405,La Chorrera,12641.497951,NaN,3,184,“No es apropiada su aplicación para la ubicaci...,Amazonas,1.004497e+06,1.264150e+10,1.264150e+06
1,9,91669,Santander,14692.132312,NaN,3,200,“No es apropiada su aplicación para la ubicaci...,Amazonas,1.178891e+06,1.469213e+10,1.469213e+06
2,11,91460,Mirití-Paraná,16813.385035,NaN,3,200,“No es apropiada su aplicación para la ubicaci...,Amazonas,7.149247e+05,1.681339e+10,1.681339e+06
3,12,91430,La Victoria,1428.202872,Ordenanza No. 012 de 1996,3,200,“No es apropiada su aplicación para la ubicaci...,Amazonas,2.754749e+05,1.428203e+09,1.428203e+05
4,17,52560,Potosí,388.676332,NaN,1,2750,“No es apropiada su aplicación para la ubicaci...,Nariño,1.426196e+05,3.886763e+08,3.886763e+04

In [4]:
Municipios.drop(columns=["OBJECTID", "MpArea", "MpNorma", "MpCategor", "Restriccion", "SHAPE_Length", "SHAPE_Area"], inplace=True)
Municipios.head()

   MpCodigo       MpNombre  MpAltitud     Depto      Area_CTM
0     91405    La Chorrera        184  Amazonas  1.264150e+06
1     91669      Santander        200  Amazonas  1.469213e+06
2     91460  Mirití-Paraná        200  Amazonas  1.681339e+06
3     91430    La Victoria        200  Amazonas  1.428203e+05
4     52560         Potosí       2750    Nariño  3.886763e+04

In [5]:
# Librerías 
import unicodedata

Caldas = Municipios[Municipios['Depto'] == 'Caldas'].copy()

# Renombrar columna
Caldas = Caldas.rename(columns={'Area_CTM': 'AREA_HA'})

# Función para quitar tildes
def quitar_tildes(texto):
    return ''.join(
        c for c in unicodedata.normalize('NFD', texto)
        if unicodedata.category(c) != 'Mn'
    )

Caldas['DEPARTAMENTO'] = Caldas['Depto'].str.upper()
Caldas['MUNICIPIO'] = Caldas['MpNombre'].apply(lambda x: quitar_tildes(x).upper())

In [6]:
Caldas

,MpCodigo,MpNombre,MpAltitud,Depto,AREA_HA,DEPARTAMENTO,MUNICIPIO
342,17873,Villamaria,1944,Caldas,45487.084767,CALDAS,VILLAMARIA
351,17088,Belalcázar,1600,Caldas,11331.640905,CALDAS,BELALCAZAR
353,17174,Chinchiná,1378,Caldas,10932.067248,CALDAS,CHINCHINA
360,17665,San José,1750,Caldas,6096.031050,CALDAS,SAN JOSE
363,17877,Viterbo,1000,Caldas,11289.618868,CALDAS,VITERBO
365,17524,Palestina,1600,Caldas,11220.389367,CALDAS,PALESTINA
374,17001,Manizales,2126,Caldas,44088.801962,CALDAS,MANIZALES
378,17616,Risaralda,1700,Caldas,8990.593398,CALDAS,RISARALDA
393,17486,Neira,1965,Caldas,36919.936572,CALDAS,NEIRA
396,17042,Anserma,1765,Caldas,20915.969799,CALDAS,ANSERMA
403,17433,Manzanares,2075,Caldas,19780.451559,CALDAS,MANZANARES
408,17444,Marquetalia,1275,Caldas,9027.744030,CALDAS,MARQUETALIA
409,17050,Aranzazu,1908,Caldas,14952.957468,CALDAS,ARANZAZU
419,17446,Marulanda,2825,Caldas,37609.138032,CALDAS,MARULANDA
420,17272,Filadelfia,1575,Caldas,19256.029993,CALDAS,FILADELFIA
435,17388,La Merced,1800,Caldas,8857.738222,CALDAS,LA MERCED
437,17653,Salamina,1793,Caldas,38795.878921,CALDAS,SALAMINA
448,17442,Marmato,1050,Caldas,3685.375172,CALDAS,MARMATO
450,17777,Supia,1184,Caldas,12143.960951,CALDAS,SUPIA
451,17541,Pensilvania,2100,Caldas,49894.378848,CALDAS,PENSILVANIA
459,17614,Riosucio,1783,Caldas,38409.536100,CALDAS,RIOSUCIO
465,17513,Pácora,1814,Caldas,25719.256617,CALDAS,PACORA
469,17867,Victoria,675,Caldas,55846.585308,CALDAS,VICTORIA
500,17013,Aguadas,2181,Caldas,47555.103067,CALDAS,AGUADAS
502,17662,Samaná,1250,Caldas,75768.425167,CALDAS,SAMANA
503,17495,Norcasia,727,Caldas,22737.856762,CALDAS,NORCASIA
511,17380,La Dorada,176,Caldas,54908.284714,CALDAS,LA DORADA

In [7]:
PROJECT_ROOT = Path().resolve().parents[1]
output_path = PROJECT_ROOT / "data" / "processed" / "municipios.csv"
print(output_path)
Caldas.to_csv(output_path, index=False, encoding='utf-8-sig')

/home/ddayann/proyectos/Coffe/proyecto_aplicado_en_analitica_de_datos/data/processed/municipios.csv