In [1]:
import os
from pathlib import Path
import pandas as pd
import numpy as np

In [2]:
# Obtener la raíz del proyecto (sube dos niveles desde notebooks/)
PROJECT_ROOT = Path().resolve().parents[1]
# Construir la ruta al archivo
data_path = PROJECT_ROOT / "data" / "raw" / "Municipios.xlsx"
print(f"Ruta del archivo: {data_path}")

Ruta del archivo: /home/ddayann/proyectos/Coffe/proyecto_aplicado_en_analitica_de_datos/data/raw/Municipios.xlsx

In [3]:
Municipios = pd.read_excel(data_path)
Municipios.head()

,DPTO,NOMBRE_DPT,MPIO,ZONA,NOMBRE_MPI,AREA,HECTARES,PERIMETER
0,44,LA GUAJIRA,847,ZONA06,URIBIA,7516770000,751676.579,475636.0
1,44,LA GUAJIRA,560,ZONA06,MANAURE,1624660000,162466.283,195961.0
2,44,LA GUAJIRA,430,ZONA06,MAICAO,1779930000,177993.385,272175.0
3,44,LA GUAJIRA,1,ZONA06,RIOHACHA,3109950000,310995.043,267347.0
4,44,LA GUAJIRA,90,ZONA06,DIBULLA,1999870000,199986.641,198795.0

In [4]:
Caldas = Municipios[Municipios['NOMBRE_DPT'] == 'CALDAS'].copy()
Caldas

,DPTO,NOMBRE_DPT,MPIO,ZONA,NOMBRE_MPI,AREA,HECTARES,PERIMETER
510,17,CALDAS,13,ZONA01,AGUADAS,501453000,50145.273,129982.0
543,17,CALDAS,513,ZONA01,PACORA,288579000,28857.945,72053.2
544,17,CALDAS,867,ZONA01,VICTORIA,528714000,52871.391,106078.0
556,17,CALDAS,541,ZONA01,PENSILVANIA,572505000,57250.506,108056.0
557,17,CALDAS,614,ZONA01,RIOSUCIO,353871000,35387.054,93035.5
561,17,CALDAS,442,ZONA01,MARMATO,40326500,4032.648,27126.6
562,17,CALDAS,777,ZONA01,SUPIA,111698000,11169.792,46052.2
570,17,CALDAS,653,ZONA01,SALAMINA,375975000,37597.505,94390.5
576,17,CALDAS,388,ZONA01,LA MERCED,90230800,9023.075,45093.2
592,17,CALDAS,272,ZONA01,FILADELFIA,202378000,20237.817,62295.6
601,17,CALDAS,50,ZONA01,ARANZAZU,140733000,14073.266,64556.9
602,17,CALDAS,446,ZONA01,MARULANDA,330317000,33031.739,91730.2
604,17,CALDAS,444,ZONA01,MARQUETALIA,81888300,8188.830,46539.4
606,17,CALDAS,433,ZONA01,MANZANARES,171947000,17194.702,61686.8
611,17,CALDAS,42,ZONA02,ANSERMA,196924000,19692.391,75389.0
614,17,CALDAS,486,ZONA01,NEIRA,407844000,40784.398,111429.0
634,17,CALDAS,616,ZONA02,RISARALDA,129563000,12956.339,82717.3
639,17,CALDAS,1,ZONA01,MANIZALES,444185000,44418.482,107380.0
642,17,CALDAS,665,ZONA01,SAN JOSE,87572400,8757.240,58478.8
648,17,CALDAS,524,ZONA01,PALESTINA,97731600,9773.163,45869.9
649,17,CALDAS,877,ZONA02,VITERBO,105855000,10585.486,48693.7
663,17,CALDAS,88,ZONA02,BELALCAZAR,114387000,11438.665,52976.8
664,17,CALDAS,174,ZONA01,CHINCHINA,125500000,12549.994,62564.4
670,17,CALDAS,873,ZONA01,VILLAMARIA,440306000,44030.594,97997.5
1105,17,CALDAS,380,ZONA01,LA DORADA,583794000,58379.399,151715.0
1106,17,CALDAS,495,ZONA01,NORCASIA,715024000,71502.394,152819.0
1107,17,CALDAS,662,ZONA01,SAMANA,318899000,31889.898,78447.7

In [5]:
PROJECT_ROOT = Path().resolve().parents[1]
output_path = PROJECT_ROOT / "data" / "processed" / "municipios.csv"
print(output_path)
Caldas.to_csv(output_path, index=False, encoding='utf-8-sig')

/home/ddayann/proyectos/Coffe/proyecto_aplicado_en_analitica_de_datos/data/processed/municipios.csv